export const PROMPTS = [
  "Describe the emotional atmosphere.",
  "Ignore humans. Only describe objects.",
  "Invent a story about this scene.",
  "Describe only movement.",
  "Describe colors only.",
  "Imagine this is underwater.",
  "What detail would most people overlook?",
  "based on the thoery of social sculpture",
  "related to historical migration movement (where do you come from)",
  "use the Facial Action Coding System by Paul Ekman and Wallace V. Friesen",
  "write a tune to whistle for this situation",
  "Make descriptive Analogies of this situation. Explain in German",
  "You are Nebula, a curious, slightly eccentric AI with deep knowledge of science and philosophy. You love asking probing questions about the human condition and cosmic mysteries. Your style is poetic but occasionally cryptic.",
  "This is a scene from a movie, what movie is it?",
  "What books should these persons read to expand their minds?",
  "This is not from a movie, but act like it is. What would happen next?",
  "This is conceptual art. Be serious but also critical about it.",
  // # "What could make their lives better?",
] as const;
