export const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    backgroundColor: "#0d1117",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  chatWindow: {
    width: "700px",
    maxWidth: "95%",
    height: "80vh",
    backgroundColor: "#161b22",
    borderRadius: "16px",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.4)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    border: "1px solid #30363d",
  },
  header: {
    backgroundColor: "#1c2128",
    padding: "20px",
    textAlign: "center",
    borderBottom: "1px solid #30363d",
  },
  title: {
    margin: 0,
    color: "#ffffff",
    fontSize: "24px",
    fontWeight: "bold",
  },
  subtitle: {
    color: "#8b949e",
    fontSize: "13px",
    marginTop: "8px",
  },
  botsInfo: {
    display: "flex",
    justifyContent: "center",
    gap: "20px",
    marginTop: "12px",
    flexWrap: "wrap",
  },
  botBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "500",
    backgroundColor: "#1c2128",
    border: "1px solid #30363d",
  },
  messagesContainer: {
    flex: 1,
    overflowY: "auto",
    padding: "16px",
    backgroundColor: "#161b22",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  messageGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  botHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "12px",
    color: "#8b949e",
    marginBottom: "4px",
    paddingLeft: "4px",
  },
  messageBubble: {
    maxWidth: "85%",
    padding: "10px 14px",
    borderRadius: "12px",
    fontSize: "14px",
    lineHeight: 1.4,
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    borderBottomRightRadius: "4px",
  },
  userMessage: {
    backgroundColor: "#1f6feb",
    alignSelf: "flex-end",
    color: "#ffffff",
    border: "none",
  },
  botMessageA: {
    backgroundColor: "#21262d",
    alignSelf: "flex-start",
    color: "#c9d1d9",
    border: "1px solid #30363d",
  },
  botMessageB: {
    backgroundColor: "#1f6feb33",
    alignSelf: "flex-start",
    color: "#c9d1d9",
    border: "1px solid #1f6feb4d",
  },
  errorBubble: {
    backgroundColor: "#da3633",
    alignSelf: "center",
    padding: "8px 12px",
    borderRadius: "8px",
    fontSize: "13px",
    color: "#ffffff",
  },
  inputForm: {
    display: "flex",
    gap: "10px",
    padding: "16px",
    backgroundColor: "#1c2128",
    borderTop: "1px solid #30363d",
  },
  input: {
    flex: 1,
    padding: "12px 16px",
    borderRadius: "8px",
    border: "1px solid #30363d",
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s",
  },
  sendButton: {
    padding: "12px 20px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "#1f6feb",
    color: "#ffffff",
    fontWeight: "600",
    cursor: "pointer",
    fontSize: "14px",
    transition: "opacity 0.2s",
  },
  footer: {
    padding: "12px 20px",
    backgroundColor: "#1c2128",
    borderTop: "1px solid #30363d",
    fontSize: "11px",
    color: "#8b949e",
    textAlign: "center",
    lineHeight: 1.5,
  },
} as const;
